name: .NET

on:
  push:
    branches: [ "main", "phase-2-docs" ]
  pull_request:
    branches: [ "main", "phase-2-docs" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore New_Extensibility_Model/Samples/Samples.sln
    - name: Build
      run: dotnet build --no-restore New_Extensibility_Model/Samples/Samples.sln